version: '3.8'

services:
  frontend:
    container_name: frontend-gazin
    image: frontend
    build:
      context: './'
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    name: gazin-crud-frontend
    driver: bridge
