version: "3.8"

services:
  frontend:
    container_name: frontend-gazin
    image: frontend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    networks:
      - frontend

  postgres:
    container_name: database-gazin
    image: postgres:12
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
      - ./backend/database_scripts:/scripts
      - ./backend/database_scripts/create_database.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=crud_gazin_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - database

networks:
  database:
    name: gazin-crud-database
    driver: bridge
  frontend:
    name: gazin-crud-frontend
    driver: bridge
